[package]
name = "cex"
version = "0.1.0"
authors = ["oooutlk <oooutlk@outlook.com>"]
license = "MIT"
keywords = [ "exception", "error", "try", "failure", "ad-hoc" ]
readme = "README.md"
repository = "https://github.com/oooutlk/enumx"
documentation = "https://docs.rs/cex"
categories = [ "rust-patterns" ]
edition = "2018"
description = "Concrete Error eXchange, or Checked EXception."

[dependencies]
enumx = { path = "../enumx" }
cex_derive = { path = "../cex_derive" }
