[package]
name = "cex_test"
version = "0.1.0"
authors = ["oooutlk <oooutlk@outlook.com>"]
license = "MIT"
edition = "2018"
publish = false

[dependencies]
cex = { path = "../cex" }
cex_derive = { path = "../cex_derive" }
